package utilitiescalculator;

import java.awt.Container;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.SystemColor;
import java.awt.Toolkit;
import java.time.YearMonth;
import javax.swing.*;

import java.util.*;

public class UCWindow extends JFrame {
    private final String propertiesFileName = "utilities.properties";
    private static final Settings SETTINGS = Settings.getInstance();
    private static final Dictionary DICT = Dictionary.INSTANCE;

    /**
     * Creates new form UCWindow
     */
    public UCWindow() {
        SETTINGS.loadProperties(propertiesFileName);
        DICT.setLanguage(SETTINGS.getLanguage());

        initComponents();

        applyLanguage();
        applySize();

        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogElecTariff = new javax.swing.JDialog();
        pnElecBoundary = new javax.swing.JPanel();
        tfElecBoundary = new javax.swing.JTextField();
        lbElecBoundary1 = new javax.swing.JLabel();
        lbElecBoundary2 = new javax.swing.JLabel();
        pnElecPrice = new javax.swing.JPanel();
        tfElecPriceBelow = new javax.swing.JTextField();
        tfElecPriceAbove = new javax.swing.JTextField();
        lbElecBelow1 = new javax.swing.JLabel();
        lbElecBelow2 = new javax.swing.JLabel();
        lbElecAbove1 = new javax.swing.JLabel();
        lbElecAbove2 = new javax.swing.JLabel();
        pnElecPrivilege = new javax.swing.JPanel();
        tfElecPrivilege = new javax.swing.JTextField();
        lbElecPrivilege1 = new javax.swing.JLabel();
        lbElecPrivilege2 = new javax.swing.JLabel();
        pnElecMaxValue = new javax.swing.JPanel();
        tfElecMaxValue = new javax.swing.JTextField();
        btElecTariffSave = new javax.swing.JButton();
        btElecTariffCancel = new javax.swing.JButton();
        dialogGasTariff = new javax.swing.JDialog();
        pnGasPrice = new javax.swing.JPanel();
        tfGasPrice = new javax.swing.JTextField();
        lbGasPrice1 = new javax.swing.JLabel();
        lbGasPrice2 = new javax.swing.JLabel();
        pnGasMaxValue = new javax.swing.JPanel();
        tfGasMaxValue = new javax.swing.JTextField();
        btGasTariffSave = new javax.swing.JButton();
        btGasTariffCancel = new javax.swing.JButton();
        dialogPersonalData = new javax.swing.JDialog();
        tfAccount = new javax.swing.JTextField();
        lbAccount = new javax.swing.JLabel();
        pnNames = new javax.swing.JPanel();
        tfSurname = new javax.swing.JTextField();
        tfFirstName = new javax.swing.JTextField();
        tfPatronymic = new javax.swing.JTextField();
        lbSurname = new javax.swing.JLabel();
        lbFirstName = new javax.swing.JLabel();
        lbPatronymic = new javax.swing.JLabel();
        pnAddress = new javax.swing.JPanel();
        tfStreet = new javax.swing.JTextField();
        tfBuilding = new javax.swing.JTextField();
        tfApartment = new javax.swing.JTextField();
        lbStreet = new javax.swing.JLabel();
        lbBuilding = new javax.swing.JLabel();
        lbApartment = new javax.swing.JLabel();
        btPersonalSave = new javax.swing.JButton();
        btPersonalCancel = new javax.swing.JButton();
        dialogViewAndPrint = new javax.swing.JDialog();
        pnDate = new javax.swing.JPanel();
        lbMonth = new javax.swing.JLabel();
        cbMonth = new javax.swing.JComboBox<>();
        lbYear = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox<>();
        pnElec = new javax.swing.JPanel();
        tfElecBegin = new javax.swing.JTextField();
        tfElecEnd = new javax.swing.JTextField();
        tfElecTotal = new javax.swing.JTextField();
        lbElecBegin = new javax.swing.JLabel();
        lbElecEnd = new javax.swing.JLabel();
        lbElecTotal = new javax.swing.JLabel();
        btElecTariff = new javax.swing.JButton();
        lbElecKwh1 = new javax.swing.JLabel();
        lbElecKwh2 = new javax.swing.JLabel();
        lbElecKwh3 = new javax.swing.JLabel();
        chbElecPanelOnOff = new javax.swing.JCheckBox();
        pnGas = new javax.swing.JPanel();
        tfGasBegin = new javax.swing.JTextField();
        tfGasEnd = new javax.swing.JTextField();
        tfGasTotal = new javax.swing.JTextField();
        lbGasBegin = new javax.swing.JLabel();
        lbGasEnd = new javax.swing.JLabel();
        lbGasTotal = new javax.swing.JLabel();
        btGasTariff = new javax.swing.JButton();
        lbGasMc1 = new javax.swing.JLabel();
        lbGasMc2 = new javax.swing.JLabel();
        lbGasMc3 = new javax.swing.JLabel();
        chbGasPanelOnOff = new javax.swing.JCheckBox();
        pnTotal = new javax.swing.JPanel();
        lbTotal = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        lbTotalGrn = new javax.swing.JLabel();
        btCalculate = new javax.swing.JButton();
        pnPayments = new javax.swing.JPanel();
        chbElec = new javax.swing.JCheckBox();
        chbRent = new javax.swing.JCheckBox();
        chbHeating = new javax.swing.JCheckBox();
        chbHotWater = new javax.swing.JCheckBox();
        chbColdWater = new javax.swing.JCheckBox();
        chbSeverage = new javax.swing.JCheckBox();
        chbGas = new javax.swing.JCheckBox();
        chbGarbage = new javax.swing.JCheckBox();
        chbIntercom = new javax.swing.JCheckBox();
        chbTv = new javax.swing.JCheckBox();
        tfElec = new javax.swing.JTextField();
        tfRent = new javax.swing.JTextField();
        tfHeating = new javax.swing.JTextField();
        tfHotWater = new javax.swing.JTextField();
        tfColdWater = new javax.swing.JTextField();
        tfSeverage = new javax.swing.JTextField();
        tfGas = new javax.swing.JTextField();
        tfGarbage = new javax.swing.JTextField();
        tfIntercom = new javax.swing.JTextField();
        tfTv = new javax.swing.JTextField();
        lbGrn1 = new javax.swing.JLabel();
        lbGrn2 = new javax.swing.JLabel();
        lbGrn3 = new javax.swing.JLabel();
        lbGrn4 = new javax.swing.JLabel();
        lbGrn5 = new javax.swing.JLabel();
        lbGrn6 = new javax.swing.JLabel();
        lbGrn7 = new javax.swing.JLabel();
        lbGrn8 = new javax.swing.JLabel();
        lbGrn9 = new javax.swing.JLabel();
        lbGrn10 = new javax.swing.JLabel();
        btViewAndPrint = new javax.swing.JButton();
        btChangeSize = new javax.swing.JButton();
        btChangeLanguage = new javax.swing.JButton();
        btPersonalData = new javax.swing.JButton();

        dialogElecTariff.setTitle("Тариф на електроенергію");
        dialogElecTariff.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        dialogElecTariff.setIconImage(null);
        dialogElecTariff.setResizable(false);

        pnElecBoundary.setBorder(javax.swing.BorderFactory.createTitledBorder("Граничний обсяг електроенергії"));

        tfElecBoundary.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbElecBoundary1.setText("Граничний обсяг електроенергії (ГОЕ):");

        lbElecBoundary2.setText("кВт·год");

        javax.swing.GroupLayout pnElecBoundaryLayout = new javax.swing.GroupLayout(pnElecBoundary);
        pnElecBoundary.setLayout(pnElecBoundaryLayout);
        pnElecBoundaryLayout.setHorizontalGroup(
            pnElecBoundaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnElecBoundaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbElecBoundary1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(tfElecBoundary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbElecBoundary2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnElecBoundaryLayout.setVerticalGroup(
            pnElecBoundaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecBoundaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnElecBoundaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElecBoundary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbElecBoundary1)
                    .addComponent(lbElecBoundary2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnElecPrice.setBorder(javax.swing.BorderFactory.createTitledBorder("Ціна на електроенергію"));

        tfElecPriceBelow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfElecPriceAbove.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbElecBelow1.setText("За обсяг, спожитий до ГОЕ:");

        lbElecBelow2.setText("копійок");

        lbElecAbove1.setText("За обсяг, спожитий понад ГОЕ:");

        lbElecAbove2.setText("копійок");

        javax.swing.GroupLayout pnElecPriceLayout = new javax.swing.GroupLayout(pnElecPrice);
        pnElecPrice.setLayout(pnElecPriceLayout);
        pnElecPriceLayout.setHorizontalGroup(
            pnElecPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnElecPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbElecBelow1)
                    .addComponent(lbElecAbove1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnElecPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfElecPriceBelow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfElecPriceAbove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnElecPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbElecBelow2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lbElecAbove2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnElecPriceLayout.setVerticalGroup(
            pnElecPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnElecPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElecPriceBelow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbElecBelow1)
                    .addComponent(lbElecBelow2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnElecPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElecPriceAbove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbElecAbove1)
                    .addComponent(lbElecAbove2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnElecPrivilege.setBorder(javax.swing.BorderFactory.createTitledBorder("Пільга"));

        tfElecPrivilege.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbElecPrivilege1.setText("Розмір пільги:");

        lbElecPrivilege2.setText("%");

        javax.swing.GroupLayout pnElecPrivilegeLayout = new javax.swing.GroupLayout(pnElecPrivilege);
        pnElecPrivilege.setLayout(pnElecPrivilegeLayout);
        pnElecPrivilegeLayout.setHorizontalGroup(
            pnElecPrivilegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnElecPrivilegeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbElecPrivilege1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfElecPrivilege, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbElecPrivilege2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnElecPrivilegeLayout.setVerticalGroup(
            pnElecPrivilegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecPrivilegeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnElecPrivilegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElecPrivilege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbElecPrivilege1)
                    .addComponent(lbElecPrivilege2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnElecMaxValue.setBorder(javax.swing.BorderFactory.createTitledBorder("Максимальне значення електричного лічильника"));

        tfElecMaxValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout pnElecMaxValueLayout = new javax.swing.GroupLayout(pnElecMaxValue);
        pnElecMaxValue.setLayout(pnElecMaxValueLayout);
        pnElecMaxValueLayout.setHorizontalGroup(
            pnElecMaxValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecMaxValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfElecMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnElecMaxValueLayout.setVerticalGroup(
            pnElecMaxValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecMaxValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfElecMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btElecTariffSave.setText("Зберегти");

        btElecTariffCancel.setText("Скасувати");

        javax.swing.GroupLayout dialogElecTariffLayout = new javax.swing.GroupLayout(dialogElecTariff.getContentPane());
        dialogElecTariff.getContentPane().setLayout(dialogElecTariffLayout);
        dialogElecTariffLayout.setHorizontalGroup(
            dialogElecTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogElecTariffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogElecTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnElecBoundary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnElecPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnElecPrivilege, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogElecTariffLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btElecTariffSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btElecTariffCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnElecMaxValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogElecTariffLayout.setVerticalGroup(
            dialogElecTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogElecTariffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnElecBoundary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnElecPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnElecPrivilege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnElecMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(dialogElecTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btElecTariffSave)
                    .addComponent(btElecTariffCancel))
                .addContainerGap())
        );

        dialogGasTariff.setTitle("Тариф на газ");
        dialogGasTariff.setResizable(false);

        pnGasPrice.setBorder(javax.swing.BorderFactory.createTitledBorder("Ціна на газ"));

        tfGasPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbGasPrice1.setText("Ціна на газ:");

        lbGasPrice2.setText("грн за м куб");

        javax.swing.GroupLayout pnGasPriceLayout = new javax.swing.GroupLayout(pnGasPrice);
        pnGasPrice.setLayout(pnGasPriceLayout);
        pnGasPriceLayout.setHorizontalGroup(
            pnGasPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGasPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGasPrice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(tfGasPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbGasPrice2)
                .addContainerGap())
        );
        pnGasPriceLayout.setVerticalGroup(
            pnGasPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGasPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGasPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGasPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGasPrice1)
                    .addComponent(lbGasPrice2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnGasMaxValue.setBorder(javax.swing.BorderFactory.createTitledBorder("Максимальне значення газового лічильника"));

        tfGasMaxValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout pnGasMaxValueLayout = new javax.swing.GroupLayout(pnGasMaxValue);
        pnGasMaxValue.setLayout(pnGasMaxValueLayout);
        pnGasMaxValueLayout.setHorizontalGroup(
            pnGasMaxValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGasMaxValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfGasMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnGasMaxValueLayout.setVerticalGroup(
            pnGasMaxValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGasMaxValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfGasMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btGasTariffSave.setText("Зберегти");

        btGasTariffCancel.setText("Скасувати");

        javax.swing.GroupLayout dialogGasTariffLayout = new javax.swing.GroupLayout(dialogGasTariff.getContentPane());
        dialogGasTariff.getContentPane().setLayout(dialogGasTariffLayout);
        dialogGasTariffLayout.setHorizontalGroup(
            dialogGasTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogGasTariffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogGasTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnGasMaxValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dialogGasTariffLayout.createSequentialGroup()
                        .addComponent(pnGasPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogGasTariffLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btGasTariffSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btGasTariffCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dialogGasTariffLayout.setVerticalGroup(
            dialogGasTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogGasTariffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnGasPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnGasMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(dialogGasTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGasTariffCancel)
                    .addComponent(btGasTariffSave))
                .addContainerGap())
        );

        dialogPersonalData.setTitle("Персональні дані платника");
        dialogPersonalData.setResizable(false);

        tfAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbAccount.setText("Особистий рахунок:");

        pnNames.setBorder(javax.swing.BorderFactory.createTitledBorder("Прізвище, ім’я та по батькові"));

        lbSurname.setText("Прізвище:");

        lbFirstName.setText("Ім’я:");

        lbPatronymic.setText("По батькові:");

        javax.swing.GroupLayout pnNamesLayout = new javax.swing.GroupLayout(pnNames);
        pnNames.setLayout(pnNamesLayout);
        pnNamesLayout.setHorizontalGroup(
            pnNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSurname)
                    .addComponent(lbFirstName)
                    .addComponent(lbPatronymic))
                .addGap(18, 18, 18)
                .addGroup(pnNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfSurname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPatronymic, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnNamesLayout.setVerticalGroup(
            pnNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFirstName)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPatronymic)
                    .addComponent(tfPatronymic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Адреса"));

        lbStreet.setText("Вулиця:");

        lbBuilding.setText("Будинок:");

        lbApartment.setText("Квартира:");

        javax.swing.GroupLayout pnAddressLayout = new javax.swing.GroupLayout(pnAddress);
        pnAddress.setLayout(pnAddressLayout);
        pnAddressLayout.setHorizontalGroup(
            pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStreet)
                    .addComponent(lbBuilding)
                    .addComponent(lbApartment))
                .addGap(18, 18, 18)
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfApartment)
                    .addComponent(tfStreet)
                    .addComponent(tfBuilding))
                .addContainerGap())
        );
        pnAddressLayout.setVerticalGroup(
            pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuilding))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbApartment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btPersonalSave.setText("Зберегти");

        btPersonalCancel.setText("Скасувати");

        javax.swing.GroupLayout dialogPersonalDataLayout = new javax.swing.GroupLayout(dialogPersonalData.getContentPane());
        dialogPersonalData.getContentPane().setLayout(dialogPersonalDataLayout);
        dialogPersonalDataLayout.setHorizontalGroup(
            dialogPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPersonalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dialogPersonalDataLayout.createSequentialGroup()
                        .addComponent(lbAccount)
                        .addGap(18, 18, 18)
                        .addComponent(tfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(pnAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPersonalDataLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btPersonalSave)
                        .addGap(18, 18, 18)
                        .addComponent(btPersonalCancel)))
                .addContainerGap())
        );
        dialogPersonalDataLayout.setVerticalGroup(
            dialogPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPersonalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAccount))
                .addGap(18, 18, 18)
                .addComponent(pnNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(dialogPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPersonalCancel)
                    .addComponent(btPersonalSave))
                .addContainerGap())
        );

        dialogViewAndPrint.setTitle("Перегляд і роздруківка");
        dialogViewAndPrint.setResizable(false);

        javax.swing.GroupLayout dialogViewAndPrintLayout = new javax.swing.GroupLayout(dialogViewAndPrint.getContentPane());
        dialogViewAndPrint.getContentPane().setLayout(dialogViewAndPrintLayout);
        dialogViewAndPrintLayout.setHorizontalGroup(
            dialogViewAndPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogViewAndPrintLayout.setVerticalGroup(
            dialogViewAndPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Сплата за комунальні послуги");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        pnDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Дата"));

        lbMonth.setText("Місяць:");

        cbMonth.setMaximumRowCount(12);
        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 - Січень", "02 - Лютий", "03 - Березень", "04 - Квітень", "05 - Травень", "06 - Червень", "07 - Липень", "08 - Серпень", "09 - Вересень", "10 - Жовтень", "11 - Листопад", "12 - Грудень" }));

        lbYear.setText("Рік:");

        javax.swing.GroupLayout pnDateLayout = new javax.swing.GroupLayout(pnDate);
        pnDate.setLayout(pnDateLayout);
        pnDateLayout.setHorizontalGroup(
            pnDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDateLayout.setVerticalGroup(
            pnDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMonth)
                    .addComponent(lbYear)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnElec.setBorder(javax.swing.BorderFactory.createTitledBorder("Показання електричного лічильника"));

        tfElecBegin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfElecEnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfElecTotal.setEditable(false);
        tfElecTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbElecBegin.setText("Початкові:");

        lbElecEnd.setText("Кінцеві:");

        lbElecTotal.setText("Різниця:");

        btElecTariff.setText("Тариф...");
        btElecTariff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElecTariffActionPerformed(evt);
            }
        });

        lbElecKwh1.setText("кВт·год");

        lbElecKwh2.setText("кВт·год");

        lbElecKwh3.setText("кВт·год");

        javax.swing.GroupLayout pnElecLayout = new javax.swing.GroupLayout(pnElec);
        pnElec.setLayout(pnElecLayout);
        pnElecLayout.setHorizontalGroup(
            pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbElecBegin)
                    .addComponent(lbElecEnd)
                    .addComponent(lbElecTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfElecEnd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfElecBegin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfElecTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnElecLayout.createSequentialGroup()
                        .addComponent(lbElecKwh3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btElecTariff))
                    .addGroup(pnElecLayout.createSequentialGroup()
                        .addComponent(lbElecKwh2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnElecLayout.createSequentialGroup()
                        .addComponent(lbElecKwh1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbElecPanelOnOff)))
                .addContainerGap())
        );
        pnElecLayout.setVerticalGroup(
            pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnElecLayout.createSequentialGroup()
                .addGroup(pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnElecLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfElecBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbElecBegin)
                            .addComponent(lbElecKwh1)))
                    .addComponent(chbElecPanelOnOff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElecEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbElecEnd)
                    .addComponent(lbElecKwh2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElecTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbElecTotal)
                    .addComponent(lbElecKwh3)
                    .addComponent(btElecTariff))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnGas.setBorder(javax.swing.BorderFactory.createTitledBorder("Показання газового лічильника"));

        tfGasBegin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfGasEnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfGasTotal.setEditable(false);
        tfGasTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbGasBegin.setText("Початкові:");

        lbGasEnd.setText("Кінцеві:");

        lbGasTotal.setText("Різниця:");

        btGasTariff.setText("Тариф...");
        btGasTariff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGasTariffActionPerformed(evt);
            }
        });

        lbGasMc1.setText("м куб");

        lbGasMc2.setText("м куб");

        lbGasMc3.setText("м куб");

        javax.swing.GroupLayout pnGasLayout = new javax.swing.GroupLayout(pnGas);
        pnGas.setLayout(pnGasLayout);
        pnGasLayout.setHorizontalGroup(
            pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGasBegin)
                    .addComponent(lbGasEnd)
                    .addComponent(lbGasTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfGasEnd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGasBegin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGasTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnGasLayout.createSequentialGroup()
                        .addComponent(lbGasMc3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btGasTariff))
                    .addGroup(pnGasLayout.createSequentialGroup()
                        .addComponent(lbGasMc2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnGasLayout.createSequentialGroup()
                        .addComponent(lbGasMc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbGasPanelOnOff)))
                .addContainerGap())
        );
        pnGasLayout.setVerticalGroup(
            pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGasLayout.createSequentialGroup()
                .addGroup(pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnGasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGasBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGasBegin)
                            .addComponent(lbGasMc1)))
                    .addComponent(chbGasPanelOnOff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGasEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGasEnd)
                    .addComponent(lbGasMc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGasTotal)
                    .addComponent(lbGasMc3)
                    .addComponent(btGasTariff))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Всього"));

        lbTotal.setText("Загалом:");

        tfTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbTotalGrn.setText("грн");

        btCalculate.setText("Розрахувати");

        javax.swing.GroupLayout pnTotalLayout = new javax.swing.GroupLayout(pnTotal);
        pnTotal.setLayout(pnTotalLayout);
        pnTotalLayout.setHorizontalGroup(
            pnTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalGrn)
                .addGap(18, 18, 18)
                .addComponent(btCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTotalLayout.setVerticalGroup(
            pnTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal)
                    .addComponent(lbTotalGrn)
                    .addComponent(btCalculate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPayments.setBorder(javax.swing.BorderFactory.createTitledBorder("Платежі"));

        chbElec.setText("01 Електроенергія:");

        chbRent.setText("02 Квартплата:");

        chbHeating.setText("03 Опалення:");

        chbHotWater.setText("04 Гаряча вода:");

        chbColdWater.setText("05 Холодна вода:");

        chbSeverage.setText("06 Каналізація:");

        chbGas.setText("07, 08 Газ природній:");

        chbGarbage.setText("33 Вивіз сміття:");

        chbIntercom.setText("35 Домофон:");

        chbTv.setText("49 Воля т.п.:");

        tfElec.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfRent.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfHeating.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfHotWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfColdWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfSeverage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfGas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfGarbage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfIntercom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfTv.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbGrn1.setText("грн");

        lbGrn2.setText("грн");

        lbGrn3.setText("грн");

        lbGrn4.setText("грн");

        lbGrn5.setText("грн");

        lbGrn6.setText("грн");

        lbGrn7.setText("грн");

        lbGrn8.setText("грн");

        lbGrn9.setText("грн");

        lbGrn10.setText("грн");

        javax.swing.GroupLayout pnPaymentsLayout = new javax.swing.GroupLayout(pnPayments);
        pnPayments.setLayout(pnPaymentsLayout);
        pnPaymentsLayout.setHorizontalGroup(
            pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbElec)
                    .addComponent(chbRent)
                    .addComponent(chbHeating)
                    .addComponent(chbHotWater)
                    .addComponent(chbColdWater)
                    .addComponent(chbSeverage)
                    .addComponent(chbGas)
                    .addComponent(chbGarbage)
                    .addComponent(chbIntercom)
                    .addComponent(chbTv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTv, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(tfIntercom)
                    .addComponent(tfGarbage)
                    .addComponent(tfGas)
                    .addComponent(tfSeverage)
                    .addComponent(tfColdWater)
                    .addComponent(tfHotWater)
                    .addComponent(tfHeating)
                    .addComponent(tfRent)
                    .addComponent(tfElec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGrn1)
                    .addComponent(lbGrn2)
                    .addComponent(lbGrn3)
                    .addComponent(lbGrn4)
                    .addComponent(lbGrn5)
                    .addComponent(lbGrn6)
                    .addComponent(lbGrn7)
                    .addComponent(lbGrn8)
                    .addComponent(lbGrn9)
                    .addComponent(lbGrn10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPaymentsLayout.setVerticalGroup(
            pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbElec)
                    .addComponent(lbGrn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbRent)
                    .addComponent(lbGrn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHeating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbHeating)
                    .addComponent(lbGrn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHotWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbHotWater)
                    .addComponent(lbGrn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfColdWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbColdWater)
                    .addComponent(lbGrn5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSeverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbSeverage)
                    .addComponent(lbGrn6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbGas)
                    .addComponent(lbGrn7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGarbage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbGarbage)
                    .addComponent(lbGrn8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIntercom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbIntercom)
                    .addComponent(lbGrn9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbTv)
                    .addComponent(lbGrn10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btViewAndPrint.setText("Роздрукувати...");
        btViewAndPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewAndPrintActionPerformed(evt);
            }
        });

        btChangeSize.setText("Шрифт(11)");
        btChangeSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeSizeActionPerformed(evt);
            }
        });

        btChangeLanguage.setText("Мова(Укр)");
        btChangeLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeLanguageActionPerformed(evt);
            }
        });

        btPersonalData.setText("Персональні дані...");
        btPersonalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPersonalDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btViewAndPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btChangeSize))
                    .addComponent(pnGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnElec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btChangeLanguage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPersonalData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnElec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPersonalData)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btChangeSize)
                        .addComponent(btChangeLanguage)
                        .addComponent(btViewAndPrint)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillDatePanel() {
        final YearMonth now = YearMonth.now();
        cbMonth.setSelectedIndex(now.getMonthValue() - 1);
        
        for (int i = -1; i <= 1; i++) {
            cbYear.addItem(Integer.toString(now.getYear() + i));
        }
        cbYear.setSelectedIndex(1);
    }
    private void fillElecPanel() {
        boolean isSelected = SETTINGS.getElecMeter();
        chbElecPanelOnOff.setSelected(isSelected);
        pnElec.setEnabled(isSelected);
        for (java.awt.Component c : pnElec.getComponents()) {
            if (c != chbElecPanelOnOff) {
                c.setEnabled(isSelected);
            }
        }
        
        String format = String.format("%%0%dd", Integer.toString(SETTINGS.getElecMeterMaxValue()).length());
        tfElecBegin.setText(String.format(format, SETTINGS.getElecBegin()));
        tfElecEnd.setText(String.format(format, SETTINGS.getElecEnd()));
        tfElecTotal.setText("" + SETTINGS.getElecTotal());
        
        tfElec.setEnabled(!isSelected);
    }
    private void fillGasPanel() {
        boolean isSelected = SETTINGS.getGasMeter();
        chbGasPanelOnOff.setSelected(isSelected);
        pnGas.setEnabled(isSelected);
        for (java.awt.Component c : pnGas.getComponents()) {
            if (c != chbGasPanelOnOff) {
                c.setEnabled(isSelected);
            }
        }
        
        String format = String.format("%%0%dd", Integer.toString(SETTINGS.getGasMeterMaxValue()).length());
        tfGasBegin.setText(String.format(format, SETTINGS.getGasBegin()));
        tfGasEnd.setText(String.format(format, SETTINGS.getGasEnd()));
        tfGasTotal.setText("" + SETTINGS.getGasTotal());
        
        tfGas.setEnabled(!isSelected);
    }
    private void fillPayments() {
        chbElec.setSelected(SETTINGS.getUsedElec());
        chbRent.setSelected(SETTINGS.getUsedRent());
        chbHeating.setSelected(SETTINGS.getUsedHeating());
        chbHotWater.setSelected(SETTINGS.getUsedHotWater());
        chbColdWater.setSelected(SETTINGS.getUsedColdWater());
        chbSeverage.setSelected(SETTINGS.getUsedSeverage());
        chbGas.setSelected(SETTINGS.getUsedGas());
        chbGarbage.setSelected(SETTINGS.getUsedGarbage());
        chbIntercom.setSelected(SETTINGS.getUsedIntercom());
        chbTv.setSelected(SETTINGS.getUsedTv());
        
        
        
    }
    
    private void fillListeners() {
        // Сохранение настроек во время закрытия окна программы:
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override public void windowClosing(java.awt.event.WindowEvent e) {
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                Dimension windowSize = getSize();
                Point location = getLocationOnScreen();
                // Если хотя бы один край окна вышел за границы рабочего стола, - центрируем позицию окна
                if ((location.getX() + windowSize.getWidth()) > screenSize.getWidth() ||
                        (location.getY() + windowSize.getHeight()) > screenSize.getHeight()) {
                    location.setLocation(screenSize.getWidth() / 2 - windowSize.getWidth() / 2,
                            screenSize.getHeight() / 2 - windowSize.getHeight() / 2);
                }
                SETTINGS.setWindowPositionX((int) location.getX());
                SETTINGS.setWindowPositionY((int) location.getY());

                SETTINGS.storeProperties(propertiesFileName);
            }
        });
        chbElecPanelOnOff.addActionListener((event) -> {
            SETTINGS.setElecMeter(!SETTINGS.getElecMeter());
            fillElecPanel();
        });
        chbGasPanelOnOff.addActionListener((event) -> {
            SETTINGS.setGasMeter(!SETTINGS.getGasMeter());
            fillGasPanel();
        });
        
        
    }

    static class MeterInputVerifier extends InputVerifier {
        private final String regex;
        private final int digitsNumber;
        MeterInputVerifier(String regex, int digitsNumber) {
            this.regex = regex;
            this.digitsNumber = digitsNumber;
        }
        @Override
        public boolean verify(JComponent component) {
            JTextField tf = (JTextField) component;
            if (!tf.getText().matches(regex)) {
                tf.setSelectionColor(SystemColor.RED);
                tf.selectAll();
                Runnable sound = (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
                if (sound != null) {
                    sound.run();
                }
                
                return false;
            }
            tf.setSelectionColor(SystemColor.textHighlight);
            
            int value = Integer.valueOf(tf.getText());
            tf.setText(String.format(String.format("%%0%dd", digitsNumber), value));
            if (tf == tfElecBegin) {
                SETTINGS.setElecBegin(value);
            } else if (tf == tfElecEnd) {
                SETTINGS.setElecEnd(value);
            } else if (tf == tfGasBegin) {
                SETTINGS.setGasBegin(value);
            } else if (tf == tfGasEnd) {
                SETTINGS.setGasEnd(value);
            } else {
                throw new RuntimeException("Some JTextField is not procceed");
            }
            tfElecTotal.setText(Integer.toString(SETTINGS.getElecTotal()));
            tfGasTotal.setText(Integer.toString(SETTINGS.getGasTotal()));
            
            return true;
        }
    }
    private void fillInputVerifiers() {
        int digitsNumber = Integer.toString(SETTINGS.getElecMeterMaxValue()).length();
        String regex = String.format("[0-9]{1,%d}", digitsNumber);

        tfElecBegin.setInputVerifier(new MeterInputVerifier(regex, digitsNumber));
        tfElecEnd.setInputVerifier(new MeterInputVerifier(regex, digitsNumber));
        
        digitsNumber = Integer.toString(SETTINGS.getGasMeterMaxValue()).length();
        regex = String.format("[0-9]{1,%d}", digitsNumber);

        tfGasBegin.setInputVerifier(new MeterInputVerifier(regex, digitsNumber));
        tfGasEnd.setInputVerifier(new MeterInputVerifier(regex, digitsNumber));
    }
    
    private void fillData() {
        fillDatePanel();
        fillElecPanel();
        fillGasPanel();
        fillPayments();
        
        fillListeners();
        fillInputVerifiers();
        
        
        
    }
    
    private static final Resizer RESIZER = Resizer.getInstance("Шрифт", Resizer.FontSize.ELEVEN);
    private static final List<Component> COMPONENTS = new ArrayList<>();
    private void holdComponents() {
        COMPONENTS.addAll(getAllComponents(this));
        COMPONENTS.addAll(getAllComponents(dialogElecTariff));
        COMPONENTS.addAll(getAllComponents(dialogGasTariff));
        COMPONENTS.addAll(getAllComponents(dialogViewAndPrint));
        COMPONENTS.addAll(getAllComponents(dialogPersonalData));
    }
    private static List<Component> getAllComponents(final Container container) {
        List<Component> components = new ArrayList<>();
        for (java.awt.Component c : container.getComponents()) {
            components.add(c);
            if (c instanceof Container) {
                components.addAll(getAllComponents((Container) c));
            }
        }
        return components;
    }
    private void applySize() {
        RESIZER.setFontSize(SETTINGS.getFontSize());
        if (COMPONENTS.isEmpty()) {
            holdComponents();
        }
        RESIZER.applyTo(COMPONENTS);
        btChangeSize.setText(RESIZER.getText());
        pack();
        dialogElecTariff.pack();
        dialogGasTariff.pack();
        dialogViewAndPrint.pack();
        dialogPersonalData.pack();
    }
    private void applyLanguage() {
        SETTINGS.setLanguage(DICT.getLanguage());
        btChangeLanguage.setText(DICT.getText());
        
        
        
    }


    private void btChangeSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeSizeActionPerformed

        RESIZER.shiftToNextFontSize();
        SETTINGS.setFontSize(RESIZER.getFontSize());
        applySize();

    }//GEN-LAST:event_btChangeSizeActionPerformed

    private void btChangeLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeLanguageActionPerformed

        DICT.setLanguage(DICT.getNextLanguage());
        applyLanguage();

    }//GEN-LAST:event_btChangeLanguageActionPerformed

    private void btViewAndPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewAndPrintActionPerformed

        dialogViewAndPrint.setLocationRelativeTo(this);
        dialogViewAndPrint.setVisible(true);
        
    }//GEN-LAST:event_btViewAndPrintActionPerformed
    
    private void btElecTariffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElecTariffActionPerformed

        dialogElecTariff.setLocationRelativeTo(this);
        dialogElecTariff.setVisible(true);
        
    }//GEN-LAST:event_btElecTariffActionPerformed

    private void btGasTariffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGasTariffActionPerformed
        
        dialogGasTariff.setLocationRelativeTo(this);
        dialogGasTariff.setVisible(true);
        
    }//GEN-LAST:event_btGasTariffActionPerformed

    private void btPersonalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPersonalDataActionPerformed
        
        dialogPersonalData.setLocationRelativeTo(this);
        dialogPersonalData.setVisible(true);
        
    }//GEN-LAST:event_btPersonalDataActionPerformed
    
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            UCWindow window = new UCWindow();
            window.setLocation(SETTINGS.getWindowPositionX(), SETTINGS.getWindowPositionY());
//            window.setLocationRelativeTo(null);
            window.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JButton btChangeLanguage;
    private javax.swing.JButton btChangeSize;
    private javax.swing.JButton btElecTariff;
    private javax.swing.JButton btElecTariffCancel;
    private javax.swing.JButton btElecTariffSave;
    private javax.swing.JButton btGasTariff;
    private javax.swing.JButton btGasTariffCancel;
    private javax.swing.JButton btGasTariffSave;
    private javax.swing.JButton btPersonalCancel;
    private javax.swing.JButton btPersonalData;
    private javax.swing.JButton btPersonalSave;
    private javax.swing.JButton btViewAndPrint;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JCheckBox chbColdWater;
    private javax.swing.JCheckBox chbElec;
    private javax.swing.JCheckBox chbElecPanelOnOff;
    private javax.swing.JCheckBox chbGarbage;
    private javax.swing.JCheckBox chbGas;
    private javax.swing.JCheckBox chbGasPanelOnOff;
    private javax.swing.JCheckBox chbHeating;
    private javax.swing.JCheckBox chbHotWater;
    private javax.swing.JCheckBox chbIntercom;
    private javax.swing.JCheckBox chbRent;
    private javax.swing.JCheckBox chbSeverage;
    private javax.swing.JCheckBox chbTv;
    private javax.swing.JDialog dialogElecTariff;
    private javax.swing.JDialog dialogGasTariff;
    private javax.swing.JDialog dialogPersonalData;
    private javax.swing.JDialog dialogViewAndPrint;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbApartment;
    private javax.swing.JLabel lbBuilding;
    private javax.swing.JLabel lbElecAbove1;
    private javax.swing.JLabel lbElecAbove2;
    private javax.swing.JLabel lbElecBegin;
    private javax.swing.JLabel lbElecBelow1;
    private javax.swing.JLabel lbElecBelow2;
    private javax.swing.JLabel lbElecBoundary1;
    private javax.swing.JLabel lbElecBoundary2;
    private javax.swing.JLabel lbElecEnd;
    private javax.swing.JLabel lbElecKwh1;
    private javax.swing.JLabel lbElecKwh2;
    private javax.swing.JLabel lbElecKwh3;
    private javax.swing.JLabel lbElecPrivilege1;
    private javax.swing.JLabel lbElecPrivilege2;
    private javax.swing.JLabel lbElecTotal;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbGasBegin;
    private javax.swing.JLabel lbGasEnd;
    private javax.swing.JLabel lbGasMc1;
    private javax.swing.JLabel lbGasMc2;
    private javax.swing.JLabel lbGasMc3;
    private javax.swing.JLabel lbGasPrice1;
    private javax.swing.JLabel lbGasPrice2;
    private javax.swing.JLabel lbGasTotal;
    private javax.swing.JLabel lbGrn1;
    private javax.swing.JLabel lbGrn10;
    private javax.swing.JLabel lbGrn2;
    private javax.swing.JLabel lbGrn3;
    private javax.swing.JLabel lbGrn4;
    private javax.swing.JLabel lbGrn5;
    private javax.swing.JLabel lbGrn6;
    private javax.swing.JLabel lbGrn7;
    private javax.swing.JLabel lbGrn8;
    private javax.swing.JLabel lbGrn9;
    private javax.swing.JLabel lbMonth;
    private javax.swing.JLabel lbPatronymic;
    private javax.swing.JLabel lbStreet;
    private javax.swing.JLabel lbSurname;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalGrn;
    private javax.swing.JLabel lbYear;
    private javax.swing.JPanel pnAddress;
    private javax.swing.JPanel pnDate;
    private javax.swing.JPanel pnElec;
    private javax.swing.JPanel pnElecBoundary;
    private javax.swing.JPanel pnElecMaxValue;
    private javax.swing.JPanel pnElecPrice;
    private javax.swing.JPanel pnElecPrivilege;
    private javax.swing.JPanel pnGas;
    private javax.swing.JPanel pnGasMaxValue;
    private javax.swing.JPanel pnGasPrice;
    private javax.swing.JPanel pnNames;
    private javax.swing.JPanel pnPayments;
    private javax.swing.JPanel pnTotal;
    private javax.swing.JTextField tfAccount;
    private javax.swing.JTextField tfApartment;
    private javax.swing.JTextField tfBuilding;
    private javax.swing.JTextField tfColdWater;
    private javax.swing.JTextField tfElec;
    private static javax.swing.JTextField tfElecBegin;
    private javax.swing.JTextField tfElecBoundary;
    private static javax.swing.JTextField tfElecEnd;
    private javax.swing.JTextField tfElecMaxValue;
    private javax.swing.JTextField tfElecPriceAbove;
    private javax.swing.JTextField tfElecPriceBelow;
    private javax.swing.JTextField tfElecPrivilege;
    private static javax.swing.JTextField tfElecTotal;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfGarbage;
    private javax.swing.JTextField tfGas;
    private static javax.swing.JTextField tfGasBegin;
    private static javax.swing.JTextField tfGasEnd;
    private javax.swing.JTextField tfGasMaxValue;
    private javax.swing.JTextField tfGasPrice;
    private static javax.swing.JTextField tfGasTotal;
    private javax.swing.JTextField tfHeating;
    private javax.swing.JTextField tfHotWater;
    private javax.swing.JTextField tfIntercom;
    private javax.swing.JTextField tfPatronymic;
    private javax.swing.JTextField tfRent;
    private javax.swing.JTextField tfSeverage;
    private javax.swing.JTextField tfStreet;
    private javax.swing.JTextField tfSurname;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTv;
    // End of variables declaration//GEN-END:variables
}
